In [5]:
import numpy as np
from sklearn.cross_validation import KFold
from sklearn import cross_validation
from sklearn.metrics import mean_squared_error #MAE
from sklearn import metrics
#scores = cross_validation.cross_val_score(clf, iris.data, iris.target, cv=5, scoring='mean_absolute_error')
#cv = cross_validation.ShuffleSplit(n_samples, n_iter=3, test_size=0.3, random_state=0)

In [6]:
kf = KFold(4,n_folds=2)
for train, test in kf:
    X = np.array([[0., 0.], [1., 1.], [-1., -1.], [2., 2.]])
    y = np.array([0, 1, 0, 1])
    X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]
    print(X_train)
    print(y_train)
    print(X_test)
    print(y_test)

[[-1. -1.]
 [ 2.  2.]]
[0 1]
[[ 0.  0.]
 [ 1.  1.]]
[0 1]
[[ 0.  0.]
 [ 1.  1.]]
[0 1]
[[-1. -1.]
 [ 2.  2.]]
[0 1]


In [7]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X,y, test_size=0.5, random_state=0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[ 1.  1.]
 [ 0.  0.]]
[1 0]
[[-1. -1.]
 [ 2.  2.]]
[0 1]
